### ISSUE TITLE
Enforce a TLD when checking?

### ISSUE THREAD

**Issue by dmlogic** [egulias/EmailValidator#188]
Hi

We've recently moved over to this library from native `filter_var($email,FILTER_VALIDATE_EMAIL)` in order to allow certain types of valid email that were failing.

This has given us a new problem - emails without a TLD are passing validation whereas they did not before. I fully understand why this is the case, but I'm wondering if there is an option to "enforce TLD" or at least generate a warning we can act on. I've found the [addTLDWarnings](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/Parser/DomainPart.php#L362) method, but I've not found anything that's using it.

Happy to do some work to enable this if you can point me in the right direction.

**Comment by dmlogic** [comment]
I'm not clear when/where it would be approprate to call `addTLDWarnings()` other than at the end of `doParseDomainLiteral()`. That method won't run unless [`hasBrackets()`](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/Parser/DomainPart.php#L157) returns true, which it does not for a value such as "me@localhost".

Sorry if I'm missing something obvious - this is the first time I've had reason to look at the source code so it's all new. I can make "me@localhost" log a warning but only if I force a call to `doParseDomainLiteral()`.

**Comment by egulias** [comment]
Sorry, my bad.

To add a TLD warning, the parser needs to do something along the lines:
1) parse untill the end of the domain part.
2) test that there where no ´Dot-string´: Atom *("."  Atom) [(see RFC 5321:4.1.2)](https://tools.ietf.org/html/rfc5321#section-4.1.2)
3) add TLD warning.

Where is wrong the parser right now:
A) ´addTLDWarnings´ is assuming it only has to add it when there's a domain literal, and should not.
B) ´parseDomainLiteral´ is not adding the TLD warning and there are not tests for that. Should be added after running [´doParseDomainLiteral´](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/Parser/DomainPart.php#L195) since any domain literal is missing TLD.
C) TLD warning is not added when there's no top level domain.

Is it more clear now? Please let me know if I'm missing something from my side too.

Thanks!

**Comment by egulias** [comment]
Fixed in v3.
