### ISSUE TITLE
version 2.1.10 causing timeouts

### ISSUE THREAD

**Issue by haid45** [egulias/EmailValidator#208]
After days of diagnoses, I have finally been able to pin point that the latest update is causing timeouts whilst laravel attempts to send mail without throwing any errors or exceptions

**Comment by egulias** [comment]
Hi @haid45 , 
Thanks for reporting. Would you mind providing more information like with which emails the timeout happens (so I can replicate in a failing test)? Does using a previous version solves the problem (to know since when the bug has been introduced)?
I'll appreciate this information to be able to help you.
