### ISSUE TITLE
EmailLexer and RFC 5322

### ISSUE THREAD

**Issue by dimitriseguin1** [egulias/EmailValidator#232]
EmailLexer use RFC-5322 to find out what character to forbid in the local-part.

But US-ASCII has not accent characters. Would it be relevant to add these special characters?

**Comment by egulias** [comment]
Hi Dimitri. You can add a US-ASCII only validator with the AND join to disallow those characters.
The question is whether the emails you are treating are USA only (English only for that matter) or have a wider scope.

**Comment by dimitriseguin1** [comment]
But it's not US emails, it will be French emails so you have to forbid all accents. It's better to make a custom validator with the same mechanics and an AND ?

**Comment by egulias** [comment]
I assumed eng because of the need to avoid accents. Yes, best option is to create `ASCIIOnlyValidator` and evaluate if any charachter in the string passed as argument to is not ascii and then use https://github.com/egulias/EmailValidator/blob/master/EmailValidator/Validation/MultipleValidationWithAnd.php
