### ISSUE TITLE
INTL_IDNA_VARIANT_2003 is deprecated since PHP 7.2

### ISSUE THREAD

**Issue by bkosborne** [egulias/EmailValidator#257]
Can this project be modified to not rely on this deprecated constant? See the [list of PHP 7.2 deprecations](https://www.php.net/manual/en/migration72.deprecated.php) for more info.

Someone already reported this in #189 but closed it for some reason.

**Comment by egulias** [comment]
Hi @bkosborne , thanks for pointing iy out. I think the previous went unnoticed becase the owner closed it.
I'll makr this one for the next version of the lib (WPI). The reason is that v2.x has to be compatible with PHP5.5.
If the replacement is available in those version then the change could be done earlier.

**Comment by kish0808** [comment]
Hi @egulias ,
Fix INTL_IDNA_VARIANT_2003 is deprecated since PHP 7.2 #257 : (https://github.com/egulias/EmailValidator/pull/264)

**Comment by egulias** [comment]
Thanks for the PR, it is valid in lower PHP versions.
Merged!
