### ISSUE TITLE
Revert changes for domains without MX

### ISSUE THREAD

**Issue by gjuric** [egulias/EmailValidator#288]
I would kindly ask you to rethink your stance on the DNS validation regarding domains with missing MX records. I am talking about the change proposed here https://github.com/egulias/EmailValidator/issues/258 and implemented in https://github.com/egulias/EmailValidator/commit/c4f703603e3e2cdcb0f5e3f957fe498874392ae3

This library is pretty popular (over 130 million installs) and is a dependency of symfony/mailer. Making it "user friendly" by proclaiming valid email addresses as invalid is not doing a service to anybody. If one wants to block these domains as well there could/should be an option for that (and drop the previous warning).

There are a lot of not ideally configure domains in the world and not accepting emails from these domains looks like is not the best approach in my opinion.

**Comment by egulias** [comment]
Hello @gjuric , thanks for sharing your thoughts. 
As far as I know, Symfony uses the NoRFCWarning validation, which checks syntaxis and fails on any warning. They do not use DNSCheckValidation by default, which is good since it requires an outside network connection to do so and it slow and adds another dependency.
I understand that there might be a lot of wrongly configured domains , however at the same time making the owners understand they have to fix it will make a better internet (and life easier) for all of us.

**Comment by gjuric** [comment]
Fair points, the problem is that the owners don't need to fix it since it is is valid per the relevant RFCs. 

It is not valid just for this library. If somebody wants to block those as well that is his right, but I think making this an option would be a more sensible approach. Whatever you decide feel free to close this issue.
