### ISSUE TITLE
Probably not an issue, but a question about the version packaged with laravel/framework v8.58.0

### ISSUE THREAD

**Issue by sscotti** [egulias/EmailValidator#303]
laravel/framework v8.58.0 requires egulias/email-validator ^2.1.10.  Kind of wondering how to upgrade that if I wanted to use the more recent version.  Kind of a novice when it comes to resolving / upgrading package dependencies.

I installed the more recent version in another MVC PHP framework and it works fine.

**Comment by egulias** [comment]
Hello @sscotti , AFAIK it will be upgraded in Laravel v9 per https://github.com/laravel/framework/pull/36525 . 

However, if you want to do it before that, v3 keeps the main interface than v2 so in theory you can change composer.json to the newest version and if the other requirements (like the PHP version) are ok, can potentially work. 
I'm not being more assertive because I don't know Laravel's inner workings to be sure it will work.

If it does, please let me know in this same issue!

**Comment by sscotti** [comment]
Thanks.  I might try that.  Would that just be in the composer.json for laravel framework ?  e.g.
```

    "require": {
        "php": "^7.3|^8.0",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "doctrine/inflector": "^1.4|^2.0",
        "dragonmantank/cron-expression": "^3.0.2",
        "egulias/email-validator": "^2.1.10",
```

Also might just wait until Laravel 9.x is released and do the upgrade then.  I installed your newest package in another composer framework I have and works fine.

`Symfony 6.0 is due for release in November. For that reason, we are choosing to delay the Laravel 9.0 release until January 2022.`

**Comment by sscotti** [comment]
I'll wait for the Laravel 9 release.
