### ISSUE TITLE
Invalid email appears valid

### ISSUE THREAD

**Issue by ghost** [egulias/EmailValidator#36]
```
$validator = new \Egulias\EmailValidator\EmailValidator();

if ($validator->isValid('test  test@example.com')) {
    echo 'valid';
}
```

Acording to the validator this email is valid.

**Comment by kskrlin** [comment]
Laravel Framework (5.8.*) uses this package to validate email adresses.

Email validation doesn't fail when email contains spaces:
"test @ example .com", but fails here "test@example. com".

If it was fixed 2014, why this bug still exists?

**Comment by robertjarec** [comment]
Why do all of these appear as valid?

' @example.com'
'###@example.com'
'$šte/-{st+email#@example.com'

**Comment by egulias** [comment]
Hi @kskrlin 

For what I can see, the bug was related to the local part (`test `), not to the domain part (`example. com`). In the unit tests you can find similar examples
* `user  name@example.com` https://github.com/egulias/EmailValidator/blob/master/Tests/EmailValidator/Validation/RFCValidationTest.php#L123
* `username@ example .com` https://github.com/egulias/EmailValidator/blob/master/Tests/EmailValidator/Validation/RFCValidationTest.php#L135
Can you please submit a PR with the failing test?
Thanks!

**Comment by egulias** [comment]
Hi @robertjarec 
Plese see:
* ` @example.com` it is an invalid email and there's a test for that: https://github.com/egulias/EmailValidator/blob/master/Tests/EmailValidator/Validation/RFCValidationTest.php#L184
* `###@example.com` is a valid email, being `#` a valid ASCII char (printable) even in the older RFCs.
* `$šte/-{st+email#@example.com` I'd say is valid from an RFC point of view. However I have my doubts reagarding `/` in the local part. If you find in the RFCs that any of those chars are invalid, please submit a PR with a test and code or PR with failing test and new issue with the justification and will fix it.

Thanks!
