### ISSUE TITLE
Index on $hostParts array looks wrong to me

### ISSUE THREAD

**Issue by nicksanders** [egulias/EmailValidator#388]
https://github.com/egulias/EmailValidator/blob/92c1ab0cc1d38e188f858cea12bbb90711fa759a/src/Validation/DNSCheckValidation.php#L89

Shouldn't it be $hostParts[(count($hostParts) - 2)] ?

**Comment by dev-kraken** [comment]
Using `count($hostParts) - 1` correctly identifies the top-level domain (TLD) because it retrieves the last element of the `hostParts` array, which is split by dots. For example, in `example.com`, `hostParts` is `['example', 'com']`, and `com` is the TLD. Using `count($hostParts) - 2` would incorrectly access the second-level domain, `example`, not the TLD.
