### ISSUE TITLE
Feature request : make a sanitization filter

### ISSUE THREAD

**Issue by kcassam** [egulias/EmailValidator#51]
Feature request : make a sanitization filter

For example, "ex@mple@tes t.com" would trim forbidden characters and result with "example@test.com"

**Comment by henriquemoody** [comment]
But since `ex@mple@tes t.com` is an invalid email, why should you sanitize it?

**Comment by kcassam** [comment]
To help find the correct email behind a typo mistake

**Comment by henriquemoody** [comment]
As I see, the point on using validation over users' inputs is to tell them they typed wrong, them they can correct it.

Perhaps you have a very particular scenario like a legacy database with many wrong inputs, in this case maybe this feature makes sense, otherwise I don't see how should it works. Even thought, there is no guarantee you will fix it correctly, the best approach IMO is to notify the user he uses a wrong email and have to create a new one instead of try to figured out how the typo was made.

Any way, it's just my 2 cents.

**Comment by kcassam** [comment]
Scenario : An smtp server. You do not control user input. For example, with Mail.app on iOS, you can send an email to 'ex@mple@tes t.com'

**Comment by egulias** [comment]
You never know which were the intent of the user. In your example `ex@test.com`is as valid as `mple@test.com` or `tes@t.com`. So is better to inform the user and let the user decide.
Maybe you should validate emails before sending them to Mail.app in iOS and let the user correct it.
Thanks for requesting the feature @kcassam but the aim of the lib is to validate, sanitization falls out of it.
You can make use of the warnings via `$validator->getWarnings()`to know which warnings an email, valid or not, has triggered.
May be would be useful to allow to know "why" the email is invalid, for example `$validator->getReason()`?

**Comment by kcassam** [comment]
OK, thanks, I fully understand your point, I'll do that in my project https://github.com/kcassam/mailcheck

**Comment by egulias** [comment]
Great!
