### ISSUE TITLE
Faster MX check

### ISSUE THREAD

**Issue by sergeyklay** [egulias/EmailValidator#76]
Hi.

It seems may faster use `dig`. 
For example:

```php
    public function isMxExists($email)
    {
        $domain = explode('@', $email);
        $domain = array_pop($domain);

        /** You can use cache here for a day. */

        exec("dig -t MX {$domain} +noall +answer +short", $result);

        return !empty($result);
    }
```

**Comment by 0x46616c6b** [comment]
Dig is not available on every server and usage of exec is not advisable.

**Comment by sergeyklay** [comment]
just add gnu linux check

**Comment by xabbuh** [comment]
This change would make it possible for a remote user to execute arbitrary commands on the server by just sending malformed e-mail addresses.

**Comment by sergeyklay** [comment]
What kind _arbitrary_ commands you are mean?

**Comment by 0x46616c6b** [comment]
`$domain = "google.com && rm -rf /var/www/* && google.com"` for example ;-)

**Comment by sergeyklay** [comment]
it's just a task. no more

```php
$str = "google.com && rm -rf /var/www/* && google.com";

$posibleDomain = explode('@', $str);
$posibleDomain = array_pop($posibleDomain);

$sanitizedDomain = explode(' ', $posibleDomain);
$sanitizedDomain = array_shift($sanitizedDomain);

var_dump($sanitizedDomain);
```

**Comment by egulias** [comment]
Hi @sergeyklay 
The usage of `exec`is generally not recommended except at your own risk when you are in control. As this lib is being used on major validation frameworks we are introducing a possible security risk.
On the other hand, an email as proposed by @0x46616c6b would fail even before reaching to the DNS check because of the domain part checking.
For the following reasons
1. `exec` introduces a possible security risk
2. When checking DNS, it is slower the network than the potential gain with the use of `exec`
3. OS dependant
I have to reject your proposal.

But do not desperate. If you look at https://github.com/egulias/EmailValidator/issues/62 you will notice that for version 2 you will be able to add your DNS check and use that one instead of the default one.

Thanks!
